server:
  port: 9770

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）

logging:
  level:
    console: INFO
    filter: INFO

spring:
  rabbitmq:
    host: 192.168.1.49
    port: 5672
    password: admin
    username: admin
  redis:
    host: 192.168.1.49
    port: 6379
    password: Uetec
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。