server:
  port: 9765
  
logging:
  common-pattern: '%d{HH:mm:ss.SSS}:[%5p] [%t] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

spring:
  rabbitmq:
    host: 192.168.1.49
    port: 5672
    password: admin
    username: admin
  redis:
    host: 192.168.1.49
    port: 6379
    password: Uetec
    key-prefix: dev
zuihou:
  mysql:
    admin:
      database: uetec_admin_dev       # 根据环境更改
    host: 192.168.1.43     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: Ae4Per62HnlG6oTysc8G7l1/c/BHVxY3VWkhKZPsh8D7cOTLHAZe2l2b7n9/aFxUkKehkNYy/u6tY65vip9how==
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。  此处mysql密码组要加密

id-generator:
  machine-code: 1  # id生成器机器掩码

test: dev_修改2
hello: dev_hello_修改2
