spring:
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.1.49 # 在hosts文件中配置地址
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://192.168.1.43:3306/uetec_admin_dev?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: Uetec123  # 这里不需要加密
# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。

logging:
  common-pattern: '%d{HH:mm:ss.SSS}:[%5p] [%t] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO